name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node 
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run liter
        run: npm run lint
      - name: Deploy
        run: |
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}            